"""Add bio and avatar to User model

Revision ID: 15545e105ab7
Revises: ca2b6582333a
Create Date: 2025-08-01 15:32:10.070560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15545e105ab7'
down_revision = 'ca2b6582333a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
